spring:
  application:
    name: config-server
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
    config:
      server:
        git:
          uri: https://github.com/BBBBigFlyPig/SpringConfigServer-Configs.git